#!/bin/bash
echo -e "\n"
check=/usr/bin/wget
if [ -f $check ]
then 
    echo "Checking dependencies....."
    sleep 2
    echo "Done"
else
    echo "Installing required packages"
    sleep 2
    sudo apt install wget -y
    sudo apt update
    echo -e "\n"
    echo "Installation done"
fi
echo -e "\n"
echo "Enter the image URL to download e.g .jpeg, .png, etc"
read n
path=`pwd`

wget --user-agent="Kali" -q -P $path $n

if [ $? -eq 0 ]
then
    echo "Image downloaded successfully at $path"
else
    echo "error occurred please check the link"
fi
